import localFont from "next/font/local";
import "./globals.css";
import CartContextProvider from "./contexts/Cart";
import { Suspense } from "react";
import Loader from "./components/Loader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< Updated upstream
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<Loader/>}>
        <CartContextProvider>{children}</CartContextProvider>
        </Suspense>
      </body>
=======
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <main className="font-[family-name:var(--font-geist-sans)] bg-white items-center">
     <Announcement />
     <Suspense fallback={<div>loading .. .</div>}>
      <Navbar clusters={clusters} />
      <CartContextProvider>{children}</CartContextProvider>
     </Suspense>
     <Footer />
    </main>
    </body>
>>>>>>> Stashed changes
    </html>
  );
}
