import localFont from "next/font/local";
import "./globals.css";
import CartContextProvider from "./contexts/Cart";
import { Suspense } from "react";
import Loader from "./components/Loader";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 // const clusters = await getClusters();
 const clusters = [];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<Loader/>}>
        <CartContextProvider>{children}</CartContextProvider>
        </Suspense>
      </body>

    </html>
);
}
