import localFont from "next/font/local";
import "./globals.css";
import CartContextProvider from "./contexts/Cart";
import Navbar from "@components/Navbar";
import Announcement from "@components/Announcement";
import Footer from "@components/Footer";
import { Suspense } from "react";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 // const clusters = await getClusters();
 const clusters = [];
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <main className="font-[family-name:var(--font-geist-sans)] bg-white items-center">
     <Announcement />
     <Navbar clusters={clusters} />
     <CartContextProvider>{children}</CartContextProvider>
     <Footer />
    </main>
    </body>
    </html>
);
}
